config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :users
  get :profile, to: 'users#profile'
  get :configure, to: 'server_groups#configure'

  resources :projects do
    member do
      get :new_user
      post :add_user
    end

    resources :server_groups do
      member do
        post :set_member
        get :deploy
      end
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :server_groups
end

app/models/server_group.rb
require "base64"

class ServerGroup < ActiveRecord::Base
  belongs_to :project

  has_many :server_group_members

  class << self
    def find_by_api_key!(api_key)
      find(Rails.application.message_verifier('server_group_api_key').verify(api_key))
    end
  end

  def api_key
    Rails.application.message_verifier('server_group_api_key').generate(id)
  end
end

app/models/server_group_member.rb
class ServerGroupMember < ActiveRecord::Base
  belongs_to :server_group, dependent: :destroy
  belongs_to :user, dependent: :destroy

  delegate :username, :ssh_public_key, :name, :preferred_shell, to: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_and_belongs_to_many :projects
  has_many :server_group_members

  def role_in(server_group)
    server_group_member = server_group_members.find_by(server_group_id: server_group.id)
    server_group_member.nil? ? 'none' : server_group_member.role
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :destroy, :new_user, :add_user]

  def index
    @projects = current_user.projects
  end

  def show
    @users = @project.users
  end

  def create
    @project = current_user.projects.create!(project_params)
  end

  def destroy
    @project.destroy!

    redirect_via_turbolinks_to root_path
  end

  def new_user
  end

  def add_user
    @user = User.find_by!(email: params[:email])
    @project.users << @user

    redirect_via_turbolinks_to project_path
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/server_groups_controller.rb
class ServerGroupsController < ApplicationController
  before_action :set_project, except: :configure
  before_action :set_server_group, only: [:destroy, :set_member, :remove_member, :deploy]
  skip_before_action :require_login, only: :configure

  def new
    @server_group = ServerGroup.new
  end

  def create
    @server_group = @project.server_groups.create!(server_group_params)

    redirect_via_turbolinks_to project_path(@project)
  end

  def destroy
    @server_group.destroy!

    redirect_via_turbolinks_to project_path(@project)
  end

  def set_member
    server_group_member = @server_group.server_group_members.find_or_initialize_by(user_id: params['user_id'])
    server_group_member.role = params['role']
    server_group_member.save!

    redirect_via_turbolinks_to project_path(@project)
  end

  def remove_member
    member = @server_group.server_group_members.find_by(user_id: params['user_id'])
    member && member.destroy!

    redirect_via_turbolinks_to project_path(@project)
  end

  def deploy

  end

  def configure
    api_key = request.headers['Authorization'].split(' ').last
    @server_group = ServerGroup.find_by_api_key!(api_key)
    @members = @server_group.server_group_members.where.not(role: 'none')
  end

  private

  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  def set_server_group
    @server_group = @project.server_groups.find(params[:id])
  end

  def server_group_params
    params.require(:server_group).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def profile
  end

  def update
    @user.update(user_params)

    redirect_to profile_path
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:username, :email, :preferred_shell, :ssh_public_key)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Avatar::View::ActionViewSupport
end

app/views/application/_footer.html.erb
<footer class="page-footer white">
  <div class="container black-text">
    <div class="row">
      Made by <a href="http://yesmeck.com">Meck</a>
    </div>
  </div>
</footer>

app/views/application/_navigation.html.erb
<nav class="light-blue lighten-1" role="navigation">
  <div class="nav-wrapper container">
    <div class="row">
      <%= link_to 'KeyHub', root_path, id: 'logo-container', class: 'brand-logo' %>
      <ul class="right hide-on-med-and-down">
        <% if signed_in? %>
          <li>
            <%= link_to current_user.email, profile_path %>
          </li>
        <% end %>
        <li>
          <% if signed_in? %>
            <%= link_to "Sign out", sign_out_path, method: :delete %>
          <% else %>
            <%= link_to "Sign in", sign_in_path %>
          <% end %>
        </li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li>
          <% if signed_in? %>
            <%= current_user.email %>
            <%= button_to "Sign out", sign_out_path, method: :delete %>
          <% else %>
            <%= link_to "Sign in", sign_in_path %>
          <% end %>
        </li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeyHub</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'navigation' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'footer' %>
  </body>
</html>

app/views/projects/_project.html.erb
<li id="<%= dom_id(project) %>" class="collection-item">
  <%= link_to project.name, project %>
</li>

app/views/projects/_server_group.html.erb
<th>
  <a class='dropdown-button btn blue' href='#' data-activates='<%= dom_id(server_group) %>-actions'><%= server_group.name %></a>

  <ul id='<%= dom_id(server_group) %>-actions' class='dropdown-content'>
    <li>
      <%= link_to 'Shell', deploy_project_server_group_path(@project, server_group), class: 'green white-text' %>
    </li>
    <li>
      <%= link_to 'Delete', project_server_group_path(@project, server_group), method: :delete, remote: true, class: 'red white-text' %>
    </li>
  </ul>
</th>

app/views/projects/_user.html.erb
<tr>
  <td><%= avatar_tag user, { size: 40 }, { class: 'circle' } %></td>
  <td><%= user.email %></td>
  <% @project.server_groups.each do |server_group| %>
    <% current_role = user.role_in(server_group) %>
    <% color = { 'root' => 'red', 'user' => 'green', 'none' => 'grey lighten-1' } %>
    <td>
      <a class='dropdown-button btn <%= color[current_role] %>' href='#' data-activates='<%= dom_id(user, dom_id(server_group)) %>-actions'><%= current_role %></a>
      <!-- Dropdown Structure -->
      <ul id='<%= dom_id(user, dom_id(server_group)) %>-actions' class='dropdown-content'>
        <% ['root', 'user', 'none'].each do |role| %>
          <% if role != current_role %>
            <li>
              <%= link_to role.upcase, set_member_project_server_group_path(@project, server_group, user_id: user.id, role: role),
                method: :post, remote: true, class: "#{color[role]} white-text" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </td>
  <% end %>
</tr>

app/views/projects/create.js.erb
$('#projects').append('<%= j render @project %>');
$('#new_project')[0].reset();

app/views/projects/index.html.erb
<div class="section">
  <div class="row">
    <h4>Projects</h4>

    <ul id="projects" class="col s12 collection">
      <%= render @projects %>
    </ul>

    <%= form_for Project.new, remote: true do |f| %>
      <div class="row">
        <div class="input-field col s6">
          <%= f.text_field :name %>
          <%= f.label :name %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s6">
          <%= f.button class: 'btn waves-effect waves-light' do %>
            Create Project
            <i class="mdi-content-send right"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/invite_user.html.erb
<div class="section">
  <div class="row">
    <h4>Invite a user to join <%= @project.name %></h4>

    <%= form_tag add_user_project_path, remote: true do %>
      <div class="row">
        <div class="input-field col s12">
          <%= text_field_tag :email, nil, placeholder: 'email@address.com' %>
        </div>
      </div>

      <div class="row">
        <div class="action-field col s12">
          <%= button_tag class: 'btn waves-effect waves-light' do %>
            Invite User
            <i class="mdi-content-send right"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new_user.html.erb
<div class="section">
  <div class="row">
    <h4>Add a new user to <%= @project.name %></h4>

    <%= form_tag add_user_project_path, remote: true do %>
      <div class="row">
        <div class="input-field col s12">
          <%= text_field_tag :email, nil, placeholder: 'email@address.com' %>
        </div>
      </div>

      <div class="row">
        <div class="action-field col s12">
          <%= button_tag class: 'btn waves-effect waves-light' do %>
            Add User
            <i class="mdi-content-send right"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="section">
  <div class="row">
    <a class='dropdown-button btn' href='#' data-activates='project-actions'><%= @project.name %></a>

    <!-- Dropdown Structure -->
    <ul id='project-actions' class='dropdown-content'>
      <li>
        <%= link_to 'Add User', new_user_project_path %>
      </li>
      <li>
        <%= link_to 'Create Server Group', new_project_server_group_path(@project) %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to 'Delete', project_path, method: :delete, remote: true, class: 'red white-text', data: { confirm: 'Are you sure delete this project?' } %>
      </li>
    </ul>

    <table class="bordered striped">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <%= render partial: 'server_group', collection: @project.server_groups %>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'user', collection: @users %>
      </tbody>
    </table>
  </div>
</div>

app/views/server_groups/deploy.html.erb
<div class="section">
  <div class="row">
    <code>
      #! /bin/bash
      <br/>
      curl -k "http://keyhub.dev/installer.sh" | api_key="<%= @server_group.api_key %>" sudo -sE
    </code>
  </div>
</div>

app/views/server_groups/new.html.erb
<div class="section">
  <div class="row">
    <h4>Create Server Group</h4>

    <%= form_for [@project, @server_group], remote: true do |f| %>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name %>
          <%= f.label :name %>
        </div>
      </div>

      <div class="row">
        <div class="action-field col s12">
          <%= button_tag class: 'btn waves-effect waves-light' do %>
            Create
            <i class="mdi-content-send right"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="section">
  <div class="row">
    <%= form_for @user, class: 'col s12' do |f| %>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :username %>
          <%= f.label :username %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name %>
          <%= f.label :name %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :email %>
          <%= f.label :email %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.select :preferred_shell, [['/bin/bash', '/bin/bash'], ['/bin/sh', '/bin/sh'] ] %>
          <%= f.label :preferred_shell %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :ssh_public_key, class: 'materialize-textarea' %>
          <%= f.label :ssh_public_key %>
        </div>
      </div>

      <div class="row">
        <div class="action-field col s12">
          <%= f.button class: 'btn waves-effect waves-light' do %>
            Submit
            <i class="mdi-content-send right"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>